### register
POST http://localhost:3000/api/v1/register
Content-Type: application/json

{
    "name":"tatang",
    "email":"tromadhona@binaracademy.org",
    "password":"password123"
}

### login
POST http://localhost:3000/api/v1/login
Content-Type: application/json

{
    "email":"tromadhona@binaracademy.org",
    "password":"password123"
}

### whoami
GET http://localhost:3000/api/v1/whoami
# Authorization: Bearer tokentoken
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWF0IjoxNzE1Nzg0NzU2fQ.ViLem0sQF8HYV629gtTvWBl06RkgIBDpY4E_Nu7wt68

### request verify email
GET http://localhost:3000/api/v1/request-verify
# Authorization: Bearer tokentoken
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWF0IjoxNzE1Nzg0NzU2fQ.ViLem0sQF8HYV629gtTvWBl06RkgIBDpY4E_Nu7wt68