POST http://localhost:3000/v1/users
Content-Type: application/json

{
    "name":"agung",
    "email":"agung@mail.com",
    "password":"agung123"
}

### get all detail
GET http://localhost:3000/v1/users

### get user detail
GET http://localhost:3000/v1/users/4


### create post
POST http://localhost:3000/v1/users/4/follow
user_id: 7