POST http://localhost:3000/v1/users
Content-Type: application/json

{
    "name":"tatang",
    "email":"tatang@mail.com",
    "password":"tatang123"
}

### get user detail
GET http://localhost:3000/v1/users/4


### create post
POST http://localhost:3000/v1/users/4/follow
user_id: 7